name: Tests

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Pin to an exact 3.9 version due to https://github.com/fudge-py/fudge/issues/13
        python-version: [3.6, 3.7, 3.8, "3.9.6"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and this library
        run: pip install -e .[test]
      - name: Run tests
        run: nosetests
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Latest python release
      - name: Install dependencies and this library
        run: pip install -e .[test]
      - name: Run MyPy
        run: mypy pyusps
